# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            My GitHub.io
tagline:          'My Website'
description:      'What about your website?'
url:              http://retrography.github.io

author:
  name:           'Me'
  url:            https://twitter.com/mszargar

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
